---
- hosts: all
  gather_facts: true
  become: true
  vars:
    sudoerlist:
    - jimjo
    - joani
    - jerry
    - damien
    
  tasks:
    
  - name: Sudoers files with copy
    copy:
      src: '{{ item }}.sudoer'
      dest: '/etc/sudoers.d/{{ item }}'
      owner: root
      group: root
      mode: 0440
      validate: 'bash -c "cat /etc/sudoers %s | visudo -cf-"'
    loop: '{{ sudoerlist }}'


  - name: Set motd using copy module
    copy:
      content: | 
        -------------------------------------------------
                This system is managed by Ansible
        -------------------------------------------------
        This is {{ ansible_fqdn }} running {{ ansible_distribution }}.
        FQDN:   {{ ansible_fqdn }}
        Distro: {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}
        Virtual: {{ 'YES' if ansible_virtualization_role == 'guest' else 'NO' }}
        CPUs:   {{ ansible_processor_vcpus }}
        RAM:    {{ (ansible_memtotal_mb / 1000) | round(1) }}GB
        Last ansible run: {{ ansible_date_time.iso8601 }}
        --------------------------------------------------
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644


  - name: Set motd using template
    template:
      src: motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644

  - name: Set 

      
  
